import { StyleSheet } from "react-native";

export const colors = {
  primary: "purple",
  surface: "white",
  text: "#000",
  mutedText: "#ccc",
  onPrimary: "white",
  shadow: "#000",
  error: "red",
};

export const globalStyles = StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: colors.primary,
  },
  databaseScreen: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "center",
    backgroundColor: colors.surface,
  },
  databaseScreenContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: colors.surface,
  },
  databaseList: {
    flex: 1,
    width: "100%",
    paddingVertical: 10,
  },
  noItemsText: {
    textAlign: "center",
    marginVertical: 20,
    color: colors.text,
  },
  card: {
    width: "80%",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 20,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginVertical: 10,
    color: colors.text,
  },
  label: {
    color: colors.text,
    paddingVertical: 5,
    textAlign: "left",
  },
  formGroup: {
    width: "100%",
    marginBottom: 5,
  },
  textField: {
    borderWidth: 1,
    borderColor: colors.mutedText,
    borderRadius: 5,
    padding: 5,
    marginBottom: 10,
    width: "100%",
  },
  numericTextField: {
    borderWidth: 1,
    borderColor: colors.mutedText,
    borderRadius: 5,
    padding: 10,
    width: 50,
    textAlign: "center",
  },
  textFieldLast: {
    marginBottom: 0,
  },
  linkButton: {
    justifyContent: "flex-start",
    borderRadius: 10,
  },
  linkText: {
    textAlign: "center",
    fontWeight: "bold",
    marginVertical: 10,
    color: colors.primary,
    marginHorizontal: 10,
  },
  formSpacer: {
    height: 20,
  },
  primaryButton: {
    width: "100%",
    backgroundColor: colors.primary,
    borderRadius: 10,
  },
  primaryButtonText: {
    textAlign: "center",
    marginVertical: 10,
    color: colors.onPrimary,
  },
  signUpText: {
    textAlign: "center",
    marginTop: 10,
    color: colors.primary,
  },
  databaseScreenHeader: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: colors.primary,
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  databaseLogOutButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    marginVertical: 10,
  },
  databaseSelectButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    marginVertical: 10,
  },
  searchBarContainer: {
    width: "100%",
    paddingHorizontal: 10,
    marginTop: 10,
    backgroundColor: colors.surface,
    flexDirection: "row",
  },
  searchBar: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.mutedText,
    borderRadius: 5,
    padding: 5,
  },
  sortButton: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  sortMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    alignItems: "flex-end",
  },
  sortMenu: {
    marginTop: 100,
    marginRight: 10,
    minWidth: 200,
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingVertical: 5,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  sortMenuOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  sortMenuOptionText: {
    color: colors.text,
    fontSize: 16,
  },
  sortMenuOptionTextSelected: {
    color: colors.primary,
    fontWeight: "bold",
  },
  sortMenuDivider: {
    height: 1,
    backgroundColor: colors.mutedText,
    marginVertical: 5,
  },
  sortMenuDirectionText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: "bold",
  },
  searchHeader: {
    width: "100%",
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.mutedText,
  },
  inventoryItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    backgroundColor: colors.surface,
    borderRadius: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    margin: 5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    padding: 20,
    backgroundColor: colors.surface,
    borderRadius: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    marginBottom: 10,
    color: colors.text,
    fontSize: 22,
    fontWeight: "bold",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 10,
  },
  modalCancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  modalCancelText: {
    color: colors.primary,
    fontWeight: "bold",
  },
  modalSaveButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
    borderRadius: 10,
  },
  modalSaveText: {
    color: colors.onPrimary,
    fontWeight: "bold",
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 24,
    zIndex: 10,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
    elevation: 8,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  modalDeleteButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.error,
  },
  modalDeleteText: {
    color: colors.error,
    fontWeight: "bold",
  },
  fallback: {
    color: colors.onPrimary,
    fontSize: 28,
    lineHeight: 32,
  },
});
