import { StyleSheet } from "react-native";

export const colors = {
  primary: "purple",
  surface: "white",
  text: "#000",
  mutedText: "#ccc",
  onPrimary: "white",
  shadow: "#000",
};

export const globalStyles = StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: colors.primary,
  },
  databaseScreen: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  databaseScreenContent: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: colors.surface,
    padding: 10,
  },
  databaseList: {
    flex: 1,
    width: "100%",
  },
  card: {
    width: "80%",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 20,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginVertical: 10,
    color: colors.text,
  },
  label: {
    color: colors.text,
    paddingVertical: 5,
    textAlign: "left",
  },
  formGroup: {
    width: "100%",
    marginBottom: 5,
  },
  textField: {
    borderWidth: 1,
    borderColor: colors.mutedText,
    borderRadius: 5,
    padding: 5,
    marginBottom: 10,
    width: "100%",
  },
  numericTextField: {
    borderWidth: 1,
    borderColor: colors.mutedText,
    borderRadius: 5,
    padding: 10,
    width: 50,
    textAlign: "center",
  },
  textFieldLast: {
    marginBottom: 0,
  },
  linkButton: {
    justifyContent: "flex-start",
    borderRadius: 10,
  },
  linkText: {
    textAlign: "center",
    fontWeight: "bold",
    marginVertical: 10,
    color: colors.primary,
    marginHorizontal: 10,
  },
  formSpacer: {
    height: 20,
  },
  primaryButton: {
    width: "100%",
    backgroundColor: colors.primary,
    borderRadius: 10,
  },
  primaryButtonText: {
    textAlign: "center",
    marginVertical: 10,
    color: colors.onPrimary,
  },
  signUpText: {
    textAlign: "center",
    marginTop: 10,
    color: colors.primary,
  },
  databaseScreenHeader: {
    width: "100%",
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  databaseSelectButton: {
    width: "80%",
    backgroundColor: colors.primary,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "flex-start",
    padding: 10,
    marginVertical: 10,
  },
  inventoryItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: 10,
    backgroundColor: colors.surface,
    borderRadius: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    marginVertical: 5,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    padding: 20,
    backgroundColor: colors.surface,
    borderRadius: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    marginBottom: 10,
    color: colors.text,
    fontSize: 22,
    fontWeight: "bold",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 10,
  },
  modalCancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  modalCancelText: {
    color: colors.primary,
    fontWeight: "bold",
  },
  modalSaveButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
    borderRadius: 10,
  },
  modalSaveText: {
    color: colors.onPrimary,
    fontWeight: "bold",
  },
});
